name: Docker build workflow

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
        description: "The full name of the image"
      push:
        required: true
        type: boolean
        description: "Whether to push the image to Docker Hub or not"
      dockerfile:
        type: string
        default: "Dockerfile"
        description: "The name of the Dockerfile (optional)"
      ping_webhook:
        type: boolean
        default: false
        description: "Whether to ping the webhook for deployment or not (optional, default false)"
      runner:
        type: string
        default: ubuntu-latest
        description: "The type of runner to use (optional)"
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      WEBHOOK_URL:
        required: false

jobs:
  build-and-push:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # 4.6.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to DHI
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # 4.6.0
        with:
          registry: dhi.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # 7.3.0
        with:
          file: ${{ inputs.dockerfile }}
          push: ${{ inputs.push }}
          tags: ${{ inputs.image-name }}
      - name: Notify webhook
        if: ${{ inputs.ping_webhook }}
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        run: |
          if [ -z "$WEBHOOK_URL" ]; then
            echo "WEBHOOK_URL secret is not configured!"
            exit 1
          fi
          curl --fail-with-body --show-error -X POST "$WEBHOOK_URL"
