name: Node.js workflow

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: ubuntu-latest
        description: "The type of runner to use (optional)"

jobs:
  install-and-lint:
    runs-on: ${{ inputs.runner }}
    outputs:
      executable: ${{ steps.find_executable.outputs.executable }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
      - id: find_executable
        name: Find executable
        run: |
          if [ -f package-lock.json ]; then
            echo "executable=npm" >> "$GITHUB_OUTPUT"
          elif [ -f yarn.lock ]; then 
            echo "executable=yarn" >> "$GITHUB_OUTPUT"
          elif [ -f bun.lockb ]; then 
            echo "executable=bun" >> "$GITHUB_OUTPUT"
          else
            echo "Not a Node.js repo, exiting."
            exit 1
          fi
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version-file: package.json
      - uses: SocketDev/action@ba6de6cc0565af1f42295590380973573297e31f # v1.3.2
        with:
          mode: firewall-free
      - name: Install dependencies
        run: sfw ${{ steps.find_executable.outputs.executable }} install
      - name: Run linter
        run: sfw ${{ steps.find_executable.outputs.executable }} run lint
      - name: Audit dependencies
        continue-on-error: true
        run: sfw ${{ steps.find_executable.outputs.executable }} audit
