name: Sonarqube workflow

on:
  workflow_call:
    inputs:
      host-url:
        type: string
        default: https://code.soulsbros.ch
        description: "Path of the Sonarqube instance (optional)"
      runner:
        type: string
        default: ubuntu-latest
        description: "The type of runner to use (optional)"
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  sonarqube:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
        with:
          fetch-depth: 0
      - uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # 8.2.1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ inputs.host-url }}
      - uses: SonarSource/sonarqube-quality-gate-action@7a5fffe8e523c40e0c740b6bc2712ab503e52efa # 1.2.1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
