name: Test

# This is only testing the Action
# DO NOT COPY THIS FILE

on:
  push:
    branches: [main]

jobs:
  build-only:
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: some-org/some-image
      push: false
      dockerfile: Dockerfile-python

  build-and-push:
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: steeven9/test
      push: true
      dockerfile: Dockerfile-python
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-and-push-and-ping:
    uses: soulsbros/CICD-template/.github/workflows/docker-build.yml@main
    with:
      image-name: steeven9/test
      push: true
      dockerfile: Dockerfile-python
      ping_webhook: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
